=== even-uia/rrs-animator/xml/boatdata.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified"
           targetNamespace="boattypelist" xmlns="boattypelist">

  <xs:element name="boatdata" type="BoatTypeList" />

  <xs:complexType name="BoatTypeList">
    <xs:sequence>
      <xs:choice maxOccurs="unbounded" >
        <xs:element name="hull" type="Hull" />
        <xs:element name="rig" type="Rig" />
        <xs:element name="polar" type="Polar" />
        <xs:element name="boattype" type="BoatType" />
      </xs:choice>
    </xs:sequence>
  </xs:complexType>

  <xs:complexType name="BoatType">
    <xs:sequence>
      <xs:choice>
        <xs:element name="hull" type="Hull"/>
        <xs:element name="hullref" type="HullRef"/>
      </xs:choice>
      <xs:choice>
        <xs:element name="rig" type="Rig"/>
        <xs:element name="rigref" type="RigRef"/>
      </xs:choice>
      <xs:choice>
        <xs:element name="polar" type="Polar"/>
        <xs:element name="polarref" type="PolarRef"/>
      </xs:choice>
    </xs:sequence>
    <xs:attribute name="id" type="xs:ID"/>
  </xs:complexType>

  <!-- Hull Definition -->
  <xs:complexType name="HullRef">
    <xs:attribute name="id" type="xs:IDREF"/>
  </xs:complexType>

  <xs:complexType name="Hull">
    <xs:sequence>
      <xs:element type="Point" name="start"/>
      <xs:choice maxOccurs="unbounded">
        <xs:element type="LineTo" name="line"/>
        <xs:element type="Spline2" name="spline2"/>
        <xs:element type="Spline3" name="spline3"/>
      </xs:choice>
    </xs:sequence>
    <xs:attribute name="id" type="xs:ID"/>
    <xs:attribute name="length" type="xs:decimal"/>
    <xs:attribute name="beam" type="xs:decimal"/>
  </xs:complexType>

  <xs:complexType name="Point">
    <xs:attributeGroup ref="point"/>
  </xs:complexType>

  <xs:complexType name="LineTo">
    <xs:attributeGroup ref="point"/>
  </xs:complexType>
  <xs:complexType name="Spline2">
    <xs:attributeGroup ref="spline2"/>
  </xs:complexType>
  <xs:complexType name="Spline3">
    <xs:attributeGroup ref="spline3"/>
  </xs:complexType>

  <xs:attributeGroup name="point">
    <xs:attribute name="x" type="xs:decimal" use="required"/>
    <xs:attribute name="y" type="xs:decimal" use="required"/>
  </xs:attributeGroup>

  <xs:attributeGroup name="spline2">
    <xs:attributeGroup ref="point"/>
    <xs:attribute name="cx1" type="xs:decimal" use="required"/>
    <xs:attribute name="cy1" type="xs:decimal" use="required"/>
  </xs:attributeGroup>

  <xs:attributeGroup name="spline3">
    <xs:attributeGroup ref="spline2"/>
    <xs:attribute name="cx2" type="xs:decimal" use="required"/>
    <xs:attribute name="cy2" type="xs:decimal" use="required"/>
  </xs:attributeGroup>

  <!-- Rig Definition -->
  <xs:complexType name="RigRef">
    <xs:attribute name="id" type="xs:IDREF"/>
  </xs:complexType>

  <xs:complexType name="Rig">
    <xs:sequence>
      <xs:element name="mast" type="Mast" minOccurs="1" maxOccurs="1" />
      <xs:element name="sail" type="Sail" minOccurs="1" maxOccurs="3"/>
    </xs:sequence>
    <xs:attribute name="id" type="xs:ID"/>
    <xs:attribute name="mintwa" type="xs:decimal"/>
    <xs:attribute name="maxtwa" type="xs:decimal"/>
  </xs:complexType>

  <xs:complexType name="Mast">
    <xs:attribute name="radius" type="xs:decimal" />
    <xs:attribute name="y" type="xs:decimal"/>
  </xs:complexType>

  <xs:complexType name="Sail">
    <xs:sequence>
      <xs:element name="spar" type="Spar"
                  minOccurs="0" maxOccurs="1" />
    </xs:sequence>
    <xs:attribute name="type" type="SailType"/>
    <xs:attribute name="pivoty" type="xs:decimal"/>
    <xs:attribute name="chord" type="xs:decimal"/>
    <xs:attribute name="camber" type="xs:decimal"/>
    <xs:attribute name="minangle" type="xs:decimal"/>
    <xs:attribute name="maxangle" type="xs:decimal"/>
  </xs:complexType>

  <xs:simpleType name="SailType">
    <xs:restriction base="xs:string">
      <xs:enumeration value="main"/>
      <xs:enumeration value="jib"/>
      <xs:enumeration value="spinnaker"/>
      <xs:enumeration value="gennaker"/>
    </xs:restriction>
  </xs:simpleType>

  <xs:complexType name="Spar">
    <xs:attribute name="type" type="SparType"/>
    <xs:attribute name="radius" type="xs:decimal"/>
    <xs:attribute name="length" type="xs:decimal"/>
  </xs:complexType>

  <xs:simpleType name="SparType">
    <xs:restriction base="xs:string">
      <xs:enumeration value="BOOM"/>
      <xs:enumeration value="POLE"/>
      <xs:enumeration value="SPRIT"/>
    </xs:restriction>
  </xs:simpleType>
  <!-- performance -->
  <xs:complexType name="PerfRef">
    <xs:attribute name="id" type="xs:IDREF"/>
  </xs:complexType>

  <xs:complexType name="PolarRef">
    <xs:attribute name="id" type="xs:IDREF"/>
  </xs:complexType>

  <xs:complexType name="Polar">
    <xs:sequence>
      <xs:element name="datum" type="Datum" minOccurs="3" maxOccurs="unbounded"/>
    </xs:sequence>
    <xs:attribute name="id" type="xs:ID"/>
  </xs:complexType>


  <xs:complexType name="Datum">
    <xs:attribute name="twa" type="Heading"/>
    <xs:attribute name="optAngle" type="xs:decimal"/>
    <xs:attribute name="optSpd" type="xs:decimal"/>
    <xs:attribute name="optA" type="xs:decimal"/>
    <xs:attribute name="slackAngle" type="xs:decimal"/>
    <xs:attribute name="slackSpd" type="xs:decimal"/>
    <xs:attribute name="slackA" type="xs:decimal"/>
    <xs:attribute name="spinSpd" type="xs:decimal"/>
  </xs:complexType>

  <xs:simpleType name="Heading">
    <xs:restriction base="xs:decimal">
      <xs:minInclusive value="0"/>
      <xs:maxInclusive value="180"/>
    </xs:restriction>
  </xs:simpleType>

</xs:schema>

=== even-uia/rrs-animator/xml/boatdata.xml
<?xml version="1.0" encoding="UTF-8"?>
<boatdata xmlns="boattypelist" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
          xsi:schemaLocation="boatdata boatdata.xsd">

  <boattype id="skiff">
    <hullref id="skiffhull"/>
    <rigref id="skiffrig"/>
    <polarref id="skiffpolar"/>
  </boattype>


  <hull id="skiffhull" beam="3" length="5">
    <start x="0" y="2.5"/>
    <line x="0.6" y="0"/>
    <line x="1.5" y="0"/>
    <line x="1.5" y="-2.4"/>
    <line x="0.6" y="-2.2"/>
    <line x="-0.6" y="-2.2"/>
    <line x="-1.5" y="-2.4"/>
    <line x="-1.5" y="0"/>
    <line x="-0.6" y="0"/>
    <line x="0" y="2.5"/>
  </hull>

  <hull id="testhull" beam="2" length="6">
    <start x="0" y="3"/>
    <spline2 cx1="1" cy1="1" x="1" y="0"/>
    <line x="2" y="0"/>
    <line x="2" y="-2"/>
  </hull>

  <rig id="skiffrig">
    <mast radius="0.07" y="0.17"/>
    <sail type="main" pivoty="0.1" chord="3" camber="0.06"
          minangle="10" maxangle="60">
      <spar type="BOOM" length="3.1" radius="0.07"/>
    </sail>
    <sail type="jib" chord="2" camber="0.08" minangle="10" maxangle="60"/>
    <sail type="gennaker" chord="3" camber="0.15"
          minangle="20" maxangle="60" pivoty="4.5"/>
  </rig>

  <polar id="skiffpolar">
    <datum twa="0" optAngle="0" optSpd="0" optA="0"
           slackAngle="0" slackSpd="0" slackA="0" spinSpd="0"/>
    <datum twa="25" optAngle="10" optSpd="5" optA="0"
           slackAngle="25" slackSpd="0" slackA="0" spinSpd="0"/>
    <datum twa="40" optAngle="15" optSpd="10" optA="0"
           slackAngle="40" slackSpd="0" slackA="0" spinSpd="0"/>
    <datum twa="50" optAngle="20" optSpd="10" optA="0"
           slackAngle="50" slackSpd="0" slackA="0" spinSpd="0"/>
    <datum twa="90" optAngle="50" optSpd="12" optA="0"
           slackAngle="70" slackSpd="6" slackA="0" spinSpd="0"/>
    <datum twa="120" optAngle="70" optSpd="12" optA="0"
           slackAngle="70" slackSpd="9" slackA="0" spinSpd="0"/>
    <datum twa="140" optAngle="70" optSpd="17" optA="0"
           slackAngle="70" slackSpd="10" slackA="0" spinSpd="17"/>
    <datum twa="150" optAngle="50" optSpd="0" optA="0"
           slackAngle="70" slackSpd="10" slackA="0" spinSpd="17"/>
    <datum twa="160" optAngle="50" optSpd="0" optA="0"
           slackAngle="70" slackSpd="8" slackA="0" spinSpd="15"/>
    <datum twa="170" optAngle="50" optSpd="7" optA="0"
           slackAngle="70" slackSpd="6" slackA="0" spinSpd="8"/>
    <datum twa="180" optAngle="40" optSpd="4" optA="0"
           slackAngle="70" slackSpd="4" slackA="0" spinSpd="5"/>
  </polar>

  <polar id="yngling">
    <datum twa="0" optAngle="0" optSpd="0" optA="0"
           slackAngle="0" slackSpd="0" slackA="0" spinSpd="0"/>
    <datum twa="40" optAngle="10" optSpd="4" optA="0"
           slackAngle="40" slackSpd="0" slackA="0" spinSpd="0"/>
    <datum twa="50" optAngle="25" optSpd="5" optA="0"
           slackAngle="50" slackSpd="0" slackA="0" spinSpd="0"/>
    <datum twa="90" optAngle="60" optSpd="5.7" optA="0"
           slackAngle="80" slackSpd="1" slackA="0" spinSpd="0"/>
    <datum twa="120" optAngle="65" optSpd="5" optA="0"
           slackAngle="80" slackSpd="2" slackA="0" spinSpd="5.6"/>
    <datum twa="150" optAngle="80" optSpd="4" optA="0"
           slackAngle="80" slackSpd="3" slackA="0" spinSpd="5"/>
    <datum twa="180" optAngle="80" optSpd="3" optA="0"
           slackAngle="80" slackSpd="3" slackA="0" spinSpd="4"/>
  </polar>

  <boattype id="singlehander">
    <hull beam="1.4" length="4.3">
      <start x="0" y="2.3"/>
      <spline2 x="0.6" y="0" cx1="0.6" cy1="1" />
      <spline2 x="0.4" y="-2" cx1="0.6" cy1="-1" />
      <line x="-0.4" y="-2"/>
      <spline2 x="-0.6" y="0" cx1="0.6" cy1="-1"/>
      <spline2 x="0" y="2.3" cx1="0.6" cy1="1"/>
    </hull>
    <rig>
      <mast radius="0.07"  y="0" />
      <sail type="main" pivoty="0.1" chord="3" camber="0.09"
            minangle="10" maxangle="88">
        <spar type="BOOM" length="3.1" radius="0.05"/>
      </sail>
    </rig>
    <polar>
      <datum twa="0" optAngle="0" optSpd="0" optA="0"
             slackAngle="0" slackSpd="0" slackA="0" spinSpd="0"/>
      <datum twa="30" optAngle="5" optSpd="1" optA="0"
             slackAngle="30" slackSpd="0" slackA="0" spinSpd="0"/>
      <datum twa="40" optAngle="10" optSpd="4" optA="0"
             slackAngle="40" slackSpd="0" slackA="0" spinSpd="0"/>
      <datum twa="50" optAngle="15" optSpd="4.3" optA="0"
             slackAngle="50" slackSpd="0" slackA="0" spinSpd="0"/>
      <datum twa="90" optAngle="50" optSpd="8" optA="0"
             slackAngle="90" slackSpd="3" slackA="0" spinSpd="0"/>
      <datum twa="140" optAngle="70" optSpd="10" optA="0"
             slackAngle="90" slackSpd="7" slackA="0" spinSpd="17"/>
      <datum twa="160" optAngle="80" optSpd="9" optA="0"
             slackAngle="90" slackSpd="8" slackA="0" spinSpd="15"/>
      <datum twa="180" optAngle="90" optSpd="6" optA="0"
             slackAngle="90" slackSpd="6" slackA="0" spinSpd="5"/>
    </polar>
  </boattype>

</boatdata>
